projects:
  pawkit:
    schemaPath: amplify/backend/api/pawkit/schema.json
    includes:
      - src/api/graphql/**/*.ts
    excludes:
      - ./amplify/**
      - src/api/graphql/API.ts
      - src/api/*.ts
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/api/graphql/API.ts
        docsFilePath: src/graphql
        region: ap-southeast-1
        apiId: null
        maxDepth: 2
extensions:
  amplify:
    version: 3
